import {titleFont, paragraphFont} from "@/assets/fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { ToastContainer } from 'react-toastify';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${titleFont.variable} ${paragraphFont.variable}`}>
      <body className={`${paragraphFont.className} `}>
      <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
      />
        {children}
      </body>
    </html>
  );
}
