import {titleFont, paragraphFont} from "@/assets/fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";
import React from "react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${titleFont.variable}`}>
      <body className={`${paragraphFont.className} `}>
        {children}
      </body>
    </html>
  );
}
